### ISSUE TITLE
Garbled output if Fix Pitch face is not „Monospace“

### ISSUE THREAD

**Issue by htgoebel** [ruediger/qrencode-el#15]
If the Fix Pitch face is not „Monspace“, the output qr code is garbled and will not be detected, see image.

![grafik](https://user-images.githubusercontent.com/784161/156221154-d838edbe-36db-458f-a867-bebb32e42615.png)

expected:
* qr code is not garbled

reproduce:

- set to a different font-family, e.g. „Hack“ - of course, this font needs to be availalbe o your system.
- create a qr-code
- watch result

**Comment by htgoebel** [comment]
Proposed solution (worked for me): Set font-familiy to “Monospace“

**Comment by ruediger** [comment]
qrencode works for me with multiple different font families. It maybe that "Hack" has particularly weird spacing settings: https://github.com/source-foundry/Hack#line-spacing-adjustments

You could either use the exported images or change the font (as you did) as workaround. Qrencode uses a separate `face` for printing the QR Code (`qrencode-face`). So you can just customize that and keep using Hack or other font families for the rest.
